instance-type = "t2.micro"
tag_name = "Dev_EC2-"
tag_name_ig = "Dev_IG"
tag_name_sg = "Dev_SG"
tag_name_subnets = "Dev_Public_Subnet-"
tag_name_rt_public = "Dev_RT_Public Subnet-"
tag_name_vpc = "Dev_VPC"